main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massivetickets.basecommand: {description: use massivetickets, default: false}
  massivetickets.list: {description: list the tickets, default: false}
  massivetickets.show: {description: show a ticket, default: false}
  massivetickets.show.other: {description: show someone elses ticket, default: false}
  massivetickets.create: {description: create a new ticket, default: false}
  massivetickets.done: {description: mark a ticket as done, default: false}
  massivetickets.done.other: {description: mark someone elses ticket as done, default: false}
  massivetickets.pick: {description: pick a ticket, default: false}
  massivetickets.yield: {description: yield a ticket, default: false}
  massivetickets.yield.other: {description: yield someone elses ticket, default: false}
  massivetickets.highscore: {description: show highscore, default: false}
  massivetickets.modlist: {description: list working moderators, default: false}
  massivetickets.working: {description: set if you are working, default: false}
  massivetickets.teleport: {description: teleport to a player, default: false}
  massivetickets.cheat: {description: give a point 4NORaisins, default: false}
  massivetickets.preference: {description: tweak your moderating experience, default: false}
  massivetickets.preference.create: {description: create new preference profiles, default: false}
  massivetickets.preference.delete: {description: delete preference profiles, default: false}
  massivetickets.preference.edit: {description: edit preference profiles, default: false}
  massivetickets.preference.edit.name: {description: edit the name of preference profiles, default: false}
  massivetickets.preference.edit.lock: {description: lock or unlock preference profiles, default: false}
  massivetickets.preference.edit.authors: {description: edit the listed authors of preference profiles, default: false}
  massivetickets.preference.edit.reaction.create: {description: edit preference profile ticket create reaction, default: false}
  massivetickets.preference.edit.reaction.pick: {description: edit preference profile ticket pick reaction, default: false}
  massivetickets.preference.edit.used: {description: select preference profiles, default: false}
  massivetickets.preference.list: {description: list preference profiles, default: false}
  massivetickets.preference.test.reaction.create: {description: test your ticket create reaction, default: false}
  massivetickets.config: {description: edit MassiveTickets config, default: false}
  massivetickets.version: {description: show plugin version, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massivetickets.*:
    children:
      massivetickets.basecommand: true
      massivetickets.list: true
      massivetickets.show: true
      massivetickets.show.other: true
      massivetickets.create: true
      massivetickets.done: true
      massivetickets.done.other: true
      massivetickets.pick: true
      massivetickets.yield: true
      massivetickets.yield.other: true
      massivetickets.highscore: true
      massivetickets.modlist: true
      massivetickets.working: true
      massivetickets.teleport: true
      massivetickets.cheat: true
      massivetickets.preference: true
      massivetickets.preference.create: true
      massivetickets.preference.delete: true
      massivetickets.preference.edit: true
      massivetickets.preference.edit.name: true
      massivetickets.preference.edit.lock: true
      massivetickets.preference.edit.authors: true
      massivetickets.preference.edit.reaction.create: true
      massivetickets.preference.edit.reaction.pick: true
      massivetickets.preference.edit.used: true
      massivetickets.preference.list: true
      massivetickets.preference.test.reaction.create: true
      massivetickets.config: true
      massivetickets.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivetickets.kit.op:
    default: op
    children:
      massivetickets.*: true
  massivetickets.kit.rank3:
    default: false
    children:
      massivetickets.kit.rank2: true
      massivetickets.preference.edit.lock: true
      massivetickets.config: true
  massivetickets.kit.rank2:
    default: false
    children:
      massivetickets.kit.rank1: true
      massivetickets.yield.other: true
      massivetickets.preference.create: true
      massivetickets.preference.delete: true
      massivetickets.preference.edit.name: true
      massivetickets.preference.edit.authors: true
      massivetickets.preference.edit.reaction.create: true
      massivetickets.preference.edit.reaction.pick: true
      massivetickets.preference.test.reaction.create: true
  massivetickets.kit.rank1:
    default: false
    children:
      massivetickets.kit.rank0: true
      massivetickets.list: true
      massivetickets.show.other: true
      massivetickets.done.other: true
      massivetickets.pick: true
      massivetickets.yield: true
      massivetickets.highscore: true
      massivetickets.working: true
      massivetickets.teleport: true
      massivetickets.preference: true
      massivetickets.preference.edit: true
      massivetickets.preference.edit.used: true
      massivetickets.preference.list: true
  massivetickets.kit.rank0:
    default: false
    children:
      massivetickets.basecommand: true
      massivetickets.show: true
      massivetickets.create: true
      massivetickets.done: true
      massivetickets.modlist: true
      massivetickets.version: true
  massivetickets.kit.default:
    default: true
    children:
      massivetickets.kit.rank0: true
